APP := profiler
OBJECTS = $(BUILD_DIR)profiler_cpuload.o $(BUILD_DIR)profiler_events.o \
          $(BUILD_DIR)profiler_pll.o $(BUILD_DIR)profiler_temp.o \
          $(BUILD_DIR)profiler_util.o $(BUILD_DIR)profiler_main.o
THUMB := 0
include $(SPINN_DIRS)/make/app.make
